application: unicornsteroids
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: WC1.html
  upload: WC1.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.+
  script: WC1.app

- url: /test.*
  script:

libraries:
- name: webapp2
  version: "2.5.1"
