<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{ title }} -{% endblock %} World Crises Database - Team Unicorn Steroids</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="World Crises Database">
    <meta name="author" content="Unicorn Steroids">
    <link rel="shortcut icon" href="/favicon.ico">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="masthead">
            <h1>World Crises Database</h1>
            <ul class="nav nav-tabs">
                <li class="{{home_active}}"><a href="/">Home</a></li>
                <li class="{{crises_active}}"><a href="/c">Crises</a></li>
                <li class="{{organizations_active}}"><a href="/o">Organizations</a></li>
                <li class="{{people_active}}"><a href="/p">People</a></li>
                <li class="{{import_active}}"><a href="/import">Import</a></li>
                <li><a target="_blank" href="/export">Export</a></li>
                <li><a target="_blank" href="/test">Tests</a></li>
                <li>
                    <form action="/search" method="post">
                      <input type="text" name="search_query" rows="1" cols="60"></input>
                      <input type="submit" value="Search"/>
                    </form>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="span12">
                {% block content %}
                    {% if crises %}
                        <h2>Crises</h2>
                        <ul>
                        {% for crisis in crises.items %}
                            <li><a href="{{ crisis.1 }}">{{ crisis.0 }}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                    {% if organizations %}
                        <h2>Organizations</h2>
                        <ul>
                        {% for organization in organizations.items %}
                            <li><a href="{{ organization.1 }}">{{ organization.0 }}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                    {% if people %}
                        <h2>People</h2>
                        <ul>
                        {% for person in people.items %}
                            <li><a href="{{ person.1 }}">{{ person.0 }}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endblock content %}
                <p>
                    <small>
                        Created by Team Unicorn Steroids : Ryan Prater, Michael Tarng, Bryan Vuong, Boris Jonica, Dereck Sanchez, Cassie Schwendiman
                    </small>
                </p>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="static/js/bootstrap.js"></script>
</body>
</html>