{% extends "object.phtml" %}

{% block type %}Organization{% endblock %}

{% block unique_data %}
            {% if object.us_phone %}
            <tr>
                <td>Phone Number</td>
                <td>{{object.us_phone}}</td>
            </tr>
            {% endif %}
            {% if object.us_email %}
            <tr>
                <td>Email Address</td>
                <td><a target="_blank" href="mailto:{{object.us_email}}">{{object.us_email}}</a></td>
            </tr>
            {% endif %}
            {% if object.us_address %}
            <tr>
                <td>Address</td>
                <td>{{object.us_address|linebreaks}}</td>
            </tr>
            {% endif %}
{% endblock %}